### PR TITLE
Changed all "to/Enum/" methods to more generic method.

### LINKED ISSUE #251: Automate all "to/Enum/" methods on the enum classes
## Task Necessity
- Right now, we have a switch-case to turn a string into an Enum Object. This switch-case has to be manually written. This is not good or extensible code-practice.

## Task Description / Solution Requirements
- Your task is to redefine the `to/Enum/` function for Enum class to be generic.
- An observation: The only thing that is necessary to see here is that this function can utilize a mapping between the Enum object, and its string value. Since such a mapping already exists, this process of finding the object based on the string value can be abstracted. 

## Authorizations (if applicable)
- N/A

## Test Requirements
- All tests should pass.

## Additional Notes
- `to/Enum` refers to the `to` method that enums have. For example, ArticleStatus: `toStatus` or Categories: `toCategory`

### PR DESCRIPTION
**Pull request by shuerry**
## Pull Request

[comment]: <> (Leave blank if a section does not apply.)

### Brief Summary
[comment]: <> (Put a brief summary of your changes.)
- Changed all "to/Enum" methods to more generic methods by utilizing the existing mapping function.
- Got rid of the switch-cases.

### Questions / Considerations for the Future
[comment]: <> (Note any questions, or things to note that might involve this PR in the future.)
- 
- 

### API Changes
[comment]: <> (Note any new endpoints, deleted endpoints, or updated endpoints.)
- 
- 

### Database Changes
[comment]: <> (Note changes to any database schemas.)
- 
- 

### New Tests
[comment]: <> (Note any new or modified test cases.)
- 
- 

[comment]: <> (Put the ticket # this PR closes.)
Closes #251

### CODE REVIEW

**Review by ethanszeto — CHANGES_REQUESTED** [review]
Looks good, thanks. We usually want to keep our test coverage up, but this doesn't actually affect any real coverage since all tests are passing, and nothing new was introduced. 

In cases like this, make sure you modify the jest.config.cjs file with the new values so CI passes.

**Review by ethanszeto — APPROVED** [review]
LGTM

**Review by suttonspindler — APPROVED** [review]
Looks good!

**Comment by ethanszeto** [comment]
I messed this up, dont review this, I will fix it

**Pull request merged**
